const mongoose =require ('mongoose')

const OrderModel = mongoose.Schema({
    shippingInfo :{
        address:{
            type:String,
            required:true
        },
        city:{
            type:String,
            required:true
        },
        state:{
            type:String,
            required:true
        },
        country:{
            type:String,
            required:true
        },
        pincode:{
            type:Number,
            required:true
        },
        phoneNo:{
            type:Number,
            required:true
        }
    },
    orderItems:[
        {
            name:{
                type:String,
                required:true
            },
            price:{
                type:Number,
                required:true
            },
            quantity:{
                type:Number,
                required:true
            },
            product:{
                type:String,
                required:true
            },
            image:{
                type:String,
                required:true
            }
        }
    ],
    user:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"user",
        required:true
    },
    paymentInfo:{
        id:{
            type:String,
            required:true
        },
        status:{
            type:String,
            required:true
        }
    },
    paidAt:{
        type:Date,
        default:Date.now()
    },
    totalPrice:{
        type:Number,
        required:true
    },
    shippingPrice:{
        type:Number,
        required:true
    },
    taxPrice:{
        type:Number,
        required:true
    },
    orderStatus:{
        type:String,
        required:true,
        default:"processing"
    },
    deliveredAt :Date,
    createdAt:{
        type:Date,
        default:Date.now()
    }
})

module.exports =mongoose.model("orders",OrderModel)